{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.componentLabels" (dict "component" "grafana" "context" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
